<a href="https://colab.research.google.com/github/syedaftab-dev/Machine-learning/blob/main/lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Full Pipeline Summary

Raw Text


   ↓


Tokenization (word → index)
   ↓


Sequences
   ↓


Padding (same length)
   ↓


Embedding (dense vectors)
   ↓


LSTM (sequence learning)
   ↓


Dense (output)
   ↓


Prediction


In [2]:
import numpy as np
import pandas as pd

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split

In [3]:
texts = [
    "I love this movie",
    "This film was terrible",
    "Amazing experience",
    "Worst acting ever",
    "I really liked it",
    "I hate this"
]

labels = [1, 0, 1, 0, 1, 0]  # 1 = positive, 0 = negative

In [4]:
vocab_size = 1000

In [5]:
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

In [6]:
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'i': 2, 'this': 3, 'love': 4, 'movie': 5, 'film': 6, 'was': 7, 'terrible': 8, 'amazing': 9, 'experience': 10, 'worst': 11, 'acting': 12, 'ever': 13, 'really': 14, 'liked': 15, 'it': 16, 'hate': 17}


In [7]:
sequences = tokenizer.texts_to_sequences(texts)
print(sequences)

[[2, 4, 3, 5], [3, 6, 7, 8], [9, 10], [11, 12, 13], [2, 14, 15, 16], [2, 17, 3]]


In [8]:
# padding
max_length = 5
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding="post", truncating="post")
print(padded_sequences)

[[ 2  4  3  5  0]
 [ 3  6  7  8  0]
 [ 9 10  0  0  0]
 [11 12 13  0  0]
 [ 2 14 15 16  0]
 [ 2 17  3  0  0]]


In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    padded_sequences, labels, test_size=0.2, random_state=42
)

In [10]:
embedding_dim = 16
model = Sequential([
    Embedding(input_dim=vocab_size,output_dim=embedding_dim, input_length=max_length),
    LSTM(32),
    Dense(1, activation="sigmoid")
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [12]:
history = model.fit(
    X_train,
    np.array(y_train),
    epochs=10,
    validation_data=(X_test, np.array(y_test))
)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.5000 - loss: 0.6929 - val_accuracy: 0.5000 - val_loss: 0.6946
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5000 - loss: 0.6923 - val_accuracy: 0.0000e+00 - val_loss: 0.6949
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.7500 - loss: 0.6917 - val_accuracy: 0.0000e+00 - val_loss: 0.6951
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.6911 - val_accuracy: 0.0000e+00 - val_loss: 0.6954
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.7500 - loss: 0.6905 - val_accuracy: 0.0000e+00 - val_loss: 0.6956
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.6898 - val_accuracy: 0.0000e+00 - val_loss: 0.6959
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 1.0000 - loss: 0.6891 - val_accuracy: 0.5000 - val_loss: 0.6961
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 1.0000 - loss: 0.6883 - val_accuracy: 0.5000 

In [13]:
loss, accuracy = model.evaluate(X_test, np.array(y_test))
print("Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6970
Accuracy: 0.5


In [14]:
test_sentence = ["I love this"]

seq = tokenizer.texts_to_sequences(test_sentence)
padded = pad_sequences(seq, maxlen=5, padding='post')

prediction = model.predict(padded)

print(prediction)  # closer to 1 → positive

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
[[0.49979255]]


🔥 Important Concepts (interview gold)

1️⃣ Tokenizer
Converts words → integers

2️⃣ Padding
Makes input fixed length

3️⃣ Embedding Layer
Learns word vectors automatically
Better than BoW / TF-IDF

4️⃣ LSTM
Captures sequence + context